# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sort_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sort_body',
            new_name='short_body',
        ),
    ]
